FROM node:20-alpine

RUN apk add --no-cache python3 py3-pip make g++ sqlite
RUN pip3 install sqlite-web --break-system-package

# Build shared
WORKDIR /shared
COPY shared/package*.json ./
RUN npm install
COPY shared/tsconfig.json ./
COPY shared/src ./src
RUN npm run build

# Setup server
WORKDIR /app

COPY server/package*.json ./

RUN npm install /shared
RUN npm ci

COPY server/tsconfig.json ./
COPY server/tsconfig.build.json ./
COPY server/src ./src

RUN npm run build:server

EXPOSE 8080
EXPOSE 8081   

CMD ["npm", "run", "dev"]
